name: localization
description: Package to simplify the package translation.
version: 2.2.0-beta.1
homepage: https://github.com/Flutterando/localization

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - test/assets/lang/
    - test/assets/lang2/
